/*
 * This source file was generated by the Gradle 'init' task
 */
package com.company.workflowautomation;
import org.springframework.boot.SpringApplication;
import org.springframework.boot.autoconfigure.SpringBootApplication;
@SpringBootApplication
public class WorkflowAutomationApplication {


    public static void main(String[] args) {
        SpringApplication.run(WorkflowAutomationApplication.class,args);
    }
}
